In [ ]:
import numpy as np

a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [ ]:
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [ ]:
a_mul = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12]])


print(a_mul[0, 2])
print(a_mul.shape)
print(a_mul.ndim)
print(a_mul.size)
print(a_mul.dtype)

3
(3, 4)
2
12
int64


In [ ]:
c = np.array([[1,2,3],
              [4,"Hello",6],
              [7,8,9]])

print(c.dtype) # it is a string
print(type(c[0][0])) # numpy string despite being integer
print(c[0][0].dtype) # U1 - string

<U21
<class 'numpy.str_'>
<U1


In [ ]:
c = np.array([[1,2,3],
              [4,"d",6],
              [7,8,9]])

print(c.dtype)

<U21


Filling arrays

In [2]:
import numpy as np
e = np.full((2,3,4), 9)
e

# 2 lists, with 3 lists and 4 records filled with one value of 9

f = np.zeros((10,5,2))
f

g = np.ones((2,4,3))
g

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
x_values = np.arange(0, 1000, 5) # the last argument is for number of step size
y_values = np.linspace(0, 1000, 4) # the last argument is for number of occuring numbers -> 0, 333, 666, 1000 this case

In [ ]:
np.nan # blanks can be replaced with np.nan and then you can drop NAN
np.inf # dividing by zero returns by infinitive value

In [ ]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]

a1 = np.array(l1)
a2 = np.array(l2)

print(l1 * 5) # python list repeated 5 times
print(a1 * 5) # multiplying each argument by five, like vectors

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


Array methods


In [ ]:
p = np.array([1,2,3])

q = np.append(p, [7,8,9])
q

s = np.insert(q, 3, [4,5,6]) # 3 is index where what is to be added
s

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
w = np.delete(a, 1) # element at this index (not list)
y = np.delete(a, 1, 0) # delete row (0 row wise deletion)

In [ ]:
np.concatenate (p,q) # append by riwsm if axis=1 added then its column wise
np.split(a, 2, axis=0) # split the array into two in first index row, axis=1 column wise

Aggregation

In [ ]:
min/max/sum/mean/median/std

Random

In [ ]:
numer = np.random.randint(100) # one value in range untill 100
numer


numers = np.random.randint(100, size=(2,3,4)) # range untill 100,size shapes the array
numers

numers2 = np.random.randint(90, 100, size=(2,3,4)) # range between 90 and 100
numers2

array([[[93, 90, 92, 97],
        [97, 99, 91, 93],
        [93, 91, 95, 98]],

       [[95, 95, 91, 95],
        [91, 90, 93, 92],
        [92, 98, 93, 98]]])

Save & Export

In [ ]:
np.save("myarray.npy", numers2)
a = np.load("myarray.npy")
a

np.savetxt("myarrayy.csv", numers2, delimiter=",")
b = np.loadtxt("myarrayy.csv", delimiter=",")

array([[[93, 90, 92, 97],
        [97, 99, 91, 93],
        [93, 91, 95, 98]],

       [[95, 95, 91, 95],
        [91, 90, 93, 92],
        [92, 98, 93, 98]]])